# Server
server:
  port: 1006
  servlet:
    context-path: /

# Spring
spring:
  # 连接池配置, spring boot 2.0默认hikariCP, pom.xml中不需额外添加依赖
  datasource:
    # 新路径 com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.198.241:3306/test?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Ak902078.
    #    type: com.alibaba.druid.pool.DruidDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariDataSource
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # redis配置
  redis:
    database: 0
    host: 116.62.198.241
    port: 6379
    password:
    # Lettuce 和 Jedis 的都是连接Redis Server的客户端程序。
    # Jedis在实现上是直连redis server，多线程环境下非线程安全，
    # 除非使用连接池，为每个Jedis实例增加物理连接。
    # Lettuce基于Netty的连接实例（StatefulRedisConnection），可以在多个线程间并发访问，且线程安全，满足多线程环境下的并发访问，
    # 同时它是可伸缩的设计，一个连接实例不够的情况也可以按需增加连接实例。
    # lettuce客户端
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8
      shutdown-timeout: 100ms
#    # jedis客户端
#    jedis:
#      pool:
#      # 最大连接数（负值表示没有限制）
#        max-active: 8
#      # 最大阻塞等待时间（负值表示没有限制）
#        max-wait: 1ms
#      # 最大空闲链接
#        max-idle: 8
#      # 最小空闲链接
#        min-idle: 0

# 日志
logging:
  level:
    # 控制日志输出级别
    root: info

